CREATE TABLE "timetracker_tasks" (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    hours INTEGER,
    priority TEXT,
    user_id INTEGER REFERENCES timetracker_users(id) ON DELETE CASCADE NOT NULL
)